name: Clone Repository

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Git Clone
        run: |
          git clone https://github.com/akhilerla/simpleAWS.git
